<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DesCoop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\SoulsFormatsNEXT\SoulsFormats\SoulsFormats.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\blocknames.txt" LogicalName="DesCoop.blocknames.txt" />
    <EmbeddedResource Include="Game\Assets\host_sigil.bc3" LogicalName="DesCoop.host_sigil.bc3" />
    <EmbeddedResource Include="Game\Assets\join_sigil.bc3" LogicalName="DesCoop.join_sigil.bc3" />
    <EmbeddedResource Include="Game\Assets\seamless_coop.lua" LogicalName="DesCoop.seamless_coop.lua" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DesCoop.Tests" />
  </ItemGroup>

</Project>
