<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>DesCoop</AssemblyName>
    <RootNamespace>DesCoop.App</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.8.0</Version>
    <Product>DeS Seamless Co-op</Product>
    <Company>himingal</Company>
    <Copyright>GPL-3.0</Copyright>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
    <SatelliteResourceLanguages>en;pt-BR</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="Fonts\Cinzel.ttf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesCoop.Core\DesCoop.Core.csproj" />
  </ItemGroup>

</Project>
